const state={coins:320,protein:42,hunger:72,energy:81,exerciseNeed:45,bond:60,sleep:7.2,exercise:1,steps:6240,damaged:false,lang:'zh',inventory:[],workouts:[]};
const $=id=>document.getElementById(id);
const i18n={
 zh:{prototype:'網頁試玩版',floor1:'1F 公寓',yourPet:'你的寵物',hunger:'飢餓',energy:'精力',exerciseNeed:'運動需求',bond:'親密度',feed:'餵食',play:'陪玩',today:'今天',wellness:'健康狀態',sleep:'睡眠',exercise:'運動',steps:'步數',syncHealth:'模擬 Apple Health 同步',ruleNote:'睡滿 8 小時可獲得每日獎勵。運動超過 4 小時後獎勵遞減，超過 20 小時後停止發放遊戲獎勵。',workout:'運動',moveEarn:'動起來，賺資源',simulateWorkout:'模擬運動',rewardExplanation:'運動獎勵依驗證後時數計算。長時間運動仍會保留紀錄，但 4 小時後獎勵遞減，20 小時後停止。',pet:'寵物',petTip:'控制好運動需求，避免寵物太無聊去破壞家具。',dailyActions:'每日互動',walkTogether:'一起散步',simulateMischief:'模擬搗蛋',resort:'度假村',buildYourSpace:'打造你的空間',cozySofa:'舒適沙發',plantCorner:'植栽角落',gymUpgrade:'健身房升級',petToy:'寵物玩具',buy:'購買',inventory:'物品欄',profile:'個人',avatarWardrobe:'角色與穿搭',homeOutfit:'居家穿搭',outfitDesc:'這是網頁試玩版的簡化預覽，iOS 版會改用真正的分層 2D 素材。',accessories:'配件',home:'首頁'},
 en:{prototype:'Web Prototype',floor1:'1F Apartment',yourPet:'Your Pet',hunger:'Hunger',energy:'Energy',exerciseNeed:'Exercise',bond:'Bond',feed:'Feed',play:'Play',today:'Today',wellness:'Wellness',sleep:'Sleep',exercise:'Exercise',steps:'Steps',syncHealth:'Simulate Apple Health Sync',ruleNote:'Sleep 8h earns a daily bonus. Exercise rewards diminish after 4h and stop after 20h.',workout:'Workout',moveEarn:'Move & Earn',simulateWorkout:'Simulate Workout',rewardExplanation:'Workout rewards are calculated from validated duration. Long sessions are still recorded, but game rewards taper after 4 hours and stop after 20 hours.',pet:'Pet',petTip:'Keep exercise need under control to prevent furniture mischief.',dailyActions:'Daily Actions',walkTogether:'Walk Together',simulateMischief:'Simulate Mischief',resort:'Resort',buildYourSpace:'Build Your Space',cozySofa:'Cozy Sofa',plantCorner:'Plant Corner',gymUpgrade:'Gym Upgrade',petToy:'Pet Toy',buy:'Buy',inventory:'Inventory',profile:'Profile',avatarWardrobe:'Avatar & Wardrobe',homeOutfit:'Home Outfit',outfitDesc:'A simple preview for the web prototype. The iOS version will use layered 2D assets.',accessories:'Accessories',home:'Home'}
};
function render(){
 $('coins').textContent=state.coins;$('protein').textContent=state.protein;$('hungerValue').textContent=`${state.hunger}%`;$('energyValue').textContent=`${state.energy}%`;$('exerciseValue').textContent=`${state.exerciseNeed}%`;$('bondValue').textContent=`${state.bond}%`;$('hungerBar').style.width=`${state.hunger}%`;$('energyBar').style.width=`${state.energy}%`;$('exerciseBar').style.width=`${state.exerciseNeed}%`;$('bondBar').style.width=`${state.bond}%`;$('sleepHours').textContent=`${state.sleep.toFixed(1)} h`;$('exerciseHours').textContent=`${state.exercise.toFixed(1)} h`;$('steps').textContent=state.steps.toLocaleString();$('damageMark').classList.toggle('show',state.damaged);$('moodBadge').textContent=state.exerciseNeed>80?'😵 Restless':state.hunger<30?'🥺 Hungry':'😊 Happy';$('petStatusTag').textContent=state.exerciseNeed>80?'Restless':'Happy';
 $('inventory').innerHTML=state.inventory.length?state.inventory.map(x=>`<span class="inventory-item">${x}</span>`).join(''):'<span style="color:#8f7f73">Empty</span>';
 $('workoutHistory').innerHTML=state.workouts.length?state.workouts.map(w=>`<div class="history-item"><div><strong>${w.type}</strong><br><small>${w.hours.toFixed(1)} h</small></div><div><strong>+${w.coins} 🪙</strong><br><small>+${w.protein} 🥩</small></div></div>`).join(''):'<div class="panel">No simulated workouts yet.</div>';
 document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(i18n[state.lang][key])el.textContent=i18n[state.lang][key]});$('langToggle').textContent=state.lang==='zh'?'EN':'中';
}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),1800)}
function rewardForHours(hours){const capped=Math.min(hours,20);let weighted=0;if(capped>0)weighted+=Math.min(capped,4);if(capped>4)weighted+=(Math.min(capped,8)-4)*.5;if(capped>8)weighted+=(Math.min(capped,12)-8)*.25;if(capped>12)weighted+=(Math.min(capped,20)-12)*.1;return weighted}
function addWorkout(hours,type='Outdoor Walk'){const weighted=rewardForHours(hours),coins=Math.round(weighted*70),protein=Math.round(weighted*10);state.exercise+=hours;state.steps+=Math.round(hours*5200);state.coins+=coins;state.protein+=protein;state.exerciseNeed=Math.max(0,state.exerciseNeed-Math.round(Math.min(hours,4)*18));state.bond=Math.min(100,state.bond+Math.round(Math.min(hours,2)*8));state.workouts.unshift({hours,type,coins,protein});if(hours>20)toast('20h cap reached — extra time recorded, no extra reward');else if(hours>4)toast('Long workout: diminishing rewards applied');else toast(`+${coins} coins · +${protein} protein`);render()}
document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(btn.dataset.target).classList.add('active')}));
$('langToggle').onclick=()=>{state.lang=state.lang==='zh'?'en':'zh';render()};
function feed(){if(state.protein<4)return toast('Not enough protein');state.protein-=4;state.hunger=Math.min(100,state.hunger+24);state.energy=Math.min(100,state.energy+5);state.bond=Math.min(100,state.bond+2);toast('Google is full and happy 🐕');render()}
$('feedBtn').onclick=feed;$('petFeedBtn').onclick=feed;
$('playBtn').onclick=()=>{state.bond=Math.min(100,state.bond+6);state.exerciseNeed=Math.max(0,state.exerciseNeed-6);toast('Bond +6');render()};
$('petExerciseBtn').onclick=()=>addWorkout(.6,'Walk with Google');
$('simulateWorkoutBtn').onclick=()=>{const options=[.5,1,2,5,9,14,21],h=options[Math.floor(Math.random()*options.length)];addWorkout(h,h<=2?'Outdoor Walk':'Long Workout Test')};
$('syncBtn').onclick=()=>{state.sleep=8.3;state.exercise=Math.max(state.exercise,1.4);state.steps=Math.max(state.steps,8420);if(!state._sleepClaimed){state.coins+=50;state.protein+=10;state._sleepClaimed=true;toast('8h sleep bonus: +50 🪙 +10 🥩')}else toast('Apple Health synced');render()};
$('mischiefBtn').onclick=()=>{state.exerciseNeed=92;state.damaged=true;toast('Google chewed the sofa! Furniture damaged.');render()};
document.querySelectorAll('.buy-btn').forEach(btn=>btn.onclick=()=>{const price=Number(btn.dataset.price);if(state.coins<price)return toast('Not enough coins');state.coins-=price;const labels={sofa:'🛋️ Cozy Sofa',plant:'🪴 Plant Corner',gym:'🏋️ Gym Upgrade',toy:'🧸 Pet Toy'};state.inventory.push(labels[btn.dataset.item]);if(btn.dataset.item==='sofa'&&state.damaged){state.damaged=false;toast('New sofa placed!')}else toast('Purchased!');render()});
render();